#!/bin/sh
#
#            DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE
#                    Version 2, December 2004
#
# Copyright (C) 2004 Sam Hocevar <sam@hocevar.net>
#
# Everyone is permitted to copy and distribute verbatim or modified
# copies of this license document, and changing it is allowed as long
# as the name is changed.
#
#            DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE
#   TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND MODIFICATION
#
#  0. You just DO WHAT THE FUCK YOU WANT TO.

if [ ${QUERY_STRING} = 'go' ]; then
	echo "Content-Type: text/plain"
	echo ""
	echo -n "Reconnecting..."
	ifup wan && echo "OK." || echo "Error."
	sleep 3
	ifconfig ppp0 | grep -F "addr"
else
	cat <<EOF
Content-Type: text/html

<!DOCTYPE html>
<html><head><title>Simple Reconnector</title><head>
<body><h1><a href="?go">Reconnect</a></h1></body></html>

EOF
fi
